//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.Web.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accoutn number.
        /// </summary>
        public static string AccoutnNumber {
            get {
                return ResourceManager.GetString("AccoutnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child.
        /// </summary>
        public static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check me out.
        /// </summary>
        public static string CheckMeOut {
            get {
                return ResourceManager.GetString("CheckMeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose any date.
        /// </summary>
        public static string ChooseAnyDate {
            get {
                return ResourceManager.GetString("ChooseAnyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose any genre.
        /// </summary>
        public static string ChooseAnyGenre {
            get {
                return ResourceManager.GetString("ChooseAnyGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose any platform.
        /// </summary>
        public static string ChooseAnyPlatform {
            get {
                return ResourceManager.GetString("ChooseAnyPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose any role.
        /// </summary>
        public static string ChooseAnyRole {
            get {
                return ResourceManager.GetString("ChooseAnyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose period.
        /// </summary>
        public static string ChoosePeriod {
            get {
                return ResourceManager.GetString("ChoosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company information.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteComment.
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this comment.
        /// </summary>
        public static string DeleteThisComment {
            get {
                return ResourceManager.GetString("DeleteThisComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value bigger than 0.
        /// </summary>
        public static string EnterBiggerThenNull {
            get {
                return ResourceManager.GetString("EnterBiggerThenNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrer description.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter key.
        /// </summary>
        public static string EnterKey {
            get {
                return ResourceManager.GetString("EnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter surname.
        /// </summary>
        public static string EnterSurname {
            get {
                return ResourceManager.GetString("EnterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOLLOW US.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM THE BLOG.
        /// </summary>
        public static string FromTheBlog {
            get {
                return ResourceManager.GetString("FromTheBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET IN TOUCH.
        /// </summary>
        public static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsBanned.
        /// </summary>
        public static string IsBanned {
            get {
                return ResourceManager.GetString("IsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDeleted.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDiscontinued.
        /// </summary>
        public static string IsDiscontinued {
            get {
                return ResourceManager.GetString("IsDiscontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPaid.
        /// </summary>
        public static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPersistent.
        /// </summary>
        public static string IsPersistent {
            get {
                return ResourceManager.GetString("IsPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsShipped.
        /// </summary>
        public static string IsShipped {
            get {
                return ResourceManager.GetString("IsShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items on page.
        /// </summary>
        public static string ItemsOnPage {
            get {
                return ResourceManager.GetString("ItemsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of games is empty.
        /// </summary>
        public static string ListOfGamesIsEmpty {
            get {
                return ResourceManager.GetString("ListOfGamesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most commented.
        /// </summary>
        public static string MostCommented {
            get {
                return ResourceManager.GetString("MostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular.
        /// </summary>
        public static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New (*by date).
        /// </summary>
        public static string NewbyDate {
            get {
                return ResourceManager.GetString("NewbyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No publisher.
        /// </summary>
        public static string NoPublisher {
            get {
                return ResourceManager.GetString("NoPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have any genres.
        /// </summary>
        public static string NotHaveGenres {
            get {
                return ResourceManager.GetString("NotHaveGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order id.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent comment had been deleted.
        /// </summary>
        public static string ParentCommentHadBeenDeleted {
            get {
                return ResourceManager.GetString("ParentCommentHadBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay using your bank.
        /// </summary>
        public static string PayUsingYourBank {
            get {
                return ResourceManager.GetString("PayUsingYourBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can pay via IBox terminal.
        /// </summary>
        public static string PayViaIbox {
            get {
                return ResourceManager.GetString("PayViaIbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can pay via Visa.
        /// </summary>
        public static string PayViaVisa {
            get {
                return ResourceManager.GetString("PayViaVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        public static string Permanent {
            get {
                return ResourceManager.GetString("Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price ASC.
        /// </summary>
        public static string PriceASC {
            get {
                return ResourceManager.GetString("PriceASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price DESC.
        /// </summary>
        public static string PriceDESC {
            get {
                return ResourceManager.GetString("PriceDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price range.
        /// </summary>
        public static string PriceRange {
            get {
                return ResourceManager.GetString("PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string RecommendedGames {
            get {
                return ResourceManager.GetString("RecommendedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can return back to game list..
        /// </summary>
        public static string RedirectToGames {
            get {
                return ResourceManager.GetString("RedirectToGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set shipped.
        /// </summary>
        public static string SetShipped {
            get {
                return ResourceManager.GetString("SetShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedDate.
        /// </summary>
        public static string ShippedDate {
            get {
                return ResourceManager.GetString("ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game was added to your basket.
        /// </summary>
        public static string ThisGameWasAddedToYourBasket {
            get {
                return ResourceManager.GetString("ThisGameWasAddedToYourBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total numbers of games.
        /// </summary>
        public static string TotalNumbersGames {
            get {
                return ResourceManager.GetString("TotalNumbersGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWITTER UPDATES.
        /// </summary>
        public static string TwitterUpdates {
            get {
                return ResourceManager.GetString("TwitterUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit in stock.
        /// </summary>
        public static string UnitInStock {
            get {
                return ResourceManager.GetString("UnitInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity.
        /// </summary>
        public static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all comments.
        /// </summary>
        public static string ViewAllComments {
            get {
                return ResourceManager.GetString("ViewAllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISIT BLOG.
        /// </summary>
        public static string VisitBlog {
            get {
                return ResourceManager.GetString("VisitBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years ago.
        /// </summary>
        public static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have just bought games!.
        /// </summary>
        public static string YouBoughtGame {
            get {
                return ResourceManager.GetString("YouBoughtGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download this game.
        /// </summary>
        public static string YouCanDownloadThisGame {
            get {
                return ResourceManager.GetString("YouCanDownloadThisGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are publisher of.
        /// </summary>
        public static string YouPublisherOf {
            get {
                return ResourceManager.GetString("YouPublisherOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your basket is empty.
        /// </summary>
        public static string YourBasketIsEmpty {
            get {
                return ResourceManager.GetString("YourBasketIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your games.
        /// </summary>
        public static string YourGames {
            get {
                return ResourceManager.GetString("YourGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сard number.
        /// </summary>
        public static string СardNumber {
            get {
                return ResourceManager.GetString("СardNumber", resourceCulture);
            }
        }
    }
}
